check for invalid 'RELEASE' values in update script
This adds two checks for invalid RELEASE values that
can potentially come from the 'update-status.json'
file.

The first checks that RELEASE is not empty. This can
happen if for example the update script was run when

the 'update-status.json' file is in its default
success state and the 'updateTo' value is an empty
string.

The second checks that RELEASE points to a valid URL
to avoid any further error from attempting to do
operations on an invalid curl call.

diff --git a/scripts/update/update b/scripts/update/update
--- a/scripts/update/update
+++ b/scripts/update/update
@@ -14,6 +14,15 @@ check_dependencies () {
   done
 }
 
+curl_check () {
+  status=$(curl -L --head --silent ${1} | grep 'HTTP.*200')
+  if echo $status | grep -q 200; then
+    return 0
+  else
+    return 1
+  fi
+}
+
 check_dependencies jq curl rsync
 
 UMBREL_ROOT="$(readlink -f $(dirname "${BASH_SOURCE[0]}")/../..)"
@@ -59,6 +68,11 @@ elif [[ "${update_type}" == "path" ]]; then
   RELEASE=$(cat "$update_path"/info.json | jq .version -r)
 fi
 
+if [[ -z "${RELEASE}" ]]; then
+  echo "Empty release version found in update-status.json file, aborting..."
+  exit 1
+fi
+
 echo
 echo "======================================="
 echo "=============== UPDATE ================"
@@ -71,6 +85,14 @@ echo
 if [[ -f "$UMBREL_ROOT/statuses/update-in-progress" ]]; then
     echo "An update is already in progress. Exiting now."
     exit 2
+fi
+
+RELEASE_URL="https://github.com/getumbrel/umbrel/archive/$RELEASE.tar.gz"
+
+# Check that release url is valid
+if ! curl_check "${RELEASE_URL}"; then
+  echo "Could not reach any release files hosted at ${RELEASE_URL}"
+  exit 1
 fi
 
 echo "Creating lock"
@@ -90,7 +112,7 @@ if [[ "${update_type}" == "ota" ]]; then
   echo "Downloading Umbrel ${RELEASE}"
   mkdir -p "${UMBREL_ROOT}/.umbrel-${RELEASE}"
   cd "${UMBREL_ROOT}/.umbrel-${RELEASE}"
-  curl -L "https://github.com/getumbrel/umbrel/archive/$RELEASE.tar.gz" | tar -xz --strip-components=1
+  curl -L "${RELEASE_URL}" | tar -xz --strip-components=1
 fi
 
 # Copy over new release from path
