Test bugfix and print error to stderr

diff --git a/scripts/backup/backup b/scripts/backup/backup
--- a/scripts/backup/backup
+++ b/scripts/backup/backup
@@ -23,9 +23,8 @@ derive_entropy () {
   identifier="${1}"
   umbrel_seed=$(cat "${UMBREL_ROOT}/db/umbrel-seed/seed") || true
 
-  # TODO: Check this correctly handles when seed file doesn't exist!
   if [[ -z "$umbrel_seed" ]] || [[ -z "$identifier" ]]; then
-    echo "Missing derivation parameter, this is unsafe, exiting."
+    >&2 echo "Missing derivation parameter, this is unsafe, exiting."
     rm -f "${UMBREL_ROOT}/statuses/backup-in-progress"
     exit 1
   fi
