Remote Tor access toggle
Co-authored-by: Luke Childs <lukechilds123@gmail.com>
Co-authored-by: Steven Briscoe <me@stevenbriscoe.com>

diff --git a/scripts/app b/scripts/app
--- a/scripts/app
+++ b/scripts/app
@@ -7,6 +7,12 @@ UMBREL_ROOT="$(readlink -f $(dirname "${BASH_SOURCE[0]}")/..)"
 USER_FILE="${UMBREL_ROOT}/db/user.json"
 ACTIVE_APP_REPO_PATH=$($UMBREL_ROOT/scripts/repo path)
 
+APP_PROXY_SERVICE_NAME="app_proxy"
+REMOTE_TOR_ACCESS="false"
+if [[ -f "${USER_FILE}" ]]; then
+  REMOTE_TOR_ACCESS=$(cat "${USER_FILE}" | jq 'has("remoteTorAccess") and .remoteTorAccess')
+fi
+
 show_help() {
   cat << EOF
 CLI (v${VERSION}) for managing Umbrel apps
@@ -17,8 +23,8 @@ Commands:
     install                    Pulls down images for an app and starts it
     uninstall                  Removes images and destroys all data for an app
     reinstall                  Calls 'uninstall', followed by 'install' for an app
-    stop                       Stops an installed app
     start                      Starts an installed app
+    stop                       Stops an installed app
     restart                    Restarts an installed app
     compose                    Passes all arguments to docker-compose
     ls-installed               Lists installed apps
@@ -57,15 +63,6 @@ derive_entropy () {
 
   # We need `sed 's/^.* //'` to trim the "(stdin)= " prefix from some versions of openssl
   printf "%s" "${identifier}" | openssl dgst -sha256 -hmac "${umbrel_seed}" | sed 's/^.* //'
-}
-
-# If the app does not provide a torrc or torrc.template file
-# Then we'll provide a default Tor torrc.template file
-copy_default_torrc_template() {
-  if [[ ! -f "${app_data_dir}/torrc.template" ]] && [[ ! -f "${app_data_dir}/torrc" ]]; then
-    local -r torrc_template_file="${UMBREL_ROOT}/scripts/support/torrc.template"
-    cp --archive "${torrc_template_file}" "${app_data_dir}"
-  fi
 }
 
 # Setup env. for this context for a given app
@@ -119,10 +116,27 @@ source_app() {
   
   export APP_DATA_DIR="${app_data_dir}"
   export APP_DOMAIN="${app_domain}"
-  export APP_HIDDEN_SERVICE="$(cat "${app_hidden_service_file}" 2>/dev/null || echo "notyetset.onion")"
+  export APP_HIDDEN_SERVICE="not-enabled.onion"
+  if [[ "${REMOTE_TOR_ACCESS}" == "true" ]]; then
+    export APP_HIDDEN_SERVICE="$(cat "${app_hidden_service_file}" 2>/dev/null || echo "notyetset.onion")"
+  fi
   export APP_SEED=$(derive_entropy "${app_entropy_identifier}")
   export APP_PASSWORD=$(derive_entropy "${app_entropy_identifier}-APP_PASSWORD")
 
+  # Tor specific exports
+  export TOR_DATA_DIR="${UMBREL_ROOT}/tor/data"
+  export TOR_ENTRYPOINT_SCRIPT="${UMBREL_ROOT}/scripts/support/tor-entrypoint.sh"
+  export TOR_HS_APP_DIR="/data/app-${app}"
+  export TOR_HS_PORTS="80:${APP_PROXY_HOSTNAME}:${APP_PROXY_PORT}"
+
+  tor_extra_hs_varname=$(echo "APP_${APP_ID^^}_TOR_HS_EXTRA_PORTS" | tr '-' '_')
+  tor_hs_extra_ports="${!tor_extra_hs_varname:-}"
+
+  if [[ ! -z "${tor_hs_extra_ports}" ]]; then
+    export TOR_HS_PORTS="${TOR_HS_PORTS} ${tor_hs_extra_ports}"
+  fi
+
+  # Other
   export UMBREL_ROOT
 }
 
@@ -149,7 +163,7 @@ else
   app="$2"
   app_repo_dir="${ACTIVE_APP_REPO_PATH}/${app}"
   app_data_dir="${UMBREL_ROOT}/app-data/${app}"
-  app_torrc_file="${app_data_dir}/torrc"
+  
   app_hidden_service_file="${UMBREL_ROOT}/tor/data/app-${app}/hostname"
   
   if [[ "${app}" == "installed" ]]; then
@@ -174,6 +188,20 @@ else
   args="${@:3}"
 fi
 
+execute_hook() {
+  local -r app="${1}"
+  local -r name="${2}"
+
+  local -r app_hooks_dir="${UMBREL_ROOT}/app-data/${app}/hooks"
+  local -r hook="${app_hooks_dir}/${name}"
+
+  if [[ -x "${hook}" ]]; then
+    echo "Executing hook: ${hook}"
+    # Swallow non-zero exit code
+    "${hook}" || true
+  fi
+}
+
 compose() {
   local -r app="${1}"
   shift
@@ -185,11 +213,9 @@ compose() {
   local -r app_proxy_compose_file="${UMBREL_ROOT}/scripts/support/docker-compose.app_proxy.yml"
   local -r tor_compose_file="${UMBREL_ROOT}/scripts/support/docker-compose.tor.yml"
   local -r common_compose_file="${UMBREL_ROOT}/scripts/support/docker-compose.common.yml"
-
-  local -r umbrel_env_file="${UMBREL_ROOT}/.env"
   local -r app_compose_file="${app_data_dir}/docker-compose.yml"
 
-  export TOR_DATA_DIR="${UMBREL_ROOT}/tor/data"
+  local -r umbrel_env_file="${UMBREL_ROOT}/.env"
 
   # We need to use the proxy compose file first
   # To allow vars. in the app's compose file to override variables
@@ -197,16 +223,15 @@ compose() {
 
   # Detect if the 'app_proxy' service has been defined
   # In the app's docker-compose file
-  APP_PROXY_SERVICE_NAME="app_proxy"
-  HAS_APP_PROXY_SERVICE=$(cat "${app_compose_file}" | yq ".services | has(\"${APP_PROXY_SERVICE_NAME}\")")
+  has_app_proxy_service=$(cat "${app_compose_file}" | yq ".services | has(\"${APP_PROXY_SERVICE_NAME}\")")
 
-  if [[ "${HAS_APP_PROXY_SERVICE}" == "true" ]]; then
+  if [[ "${has_app_proxy_service}" == "true" ]]; then
     compose_files+=( "--file" "${app_proxy_compose_file}" )
   fi
-  
-  # If an app has a torrc file
+
+  # If remote Tor access is enabled
   # Then include a compose file for Tor
-  if [[ -f "${app_torrc_file}" ]]; then
+  if [[ "${REMOTE_TOR_ACCESS}" == "true" ]]; then
     compose_files+=( "--file" "${tor_compose_file}" )
   fi
 
@@ -268,7 +293,7 @@ copy_app_files() {
     APP_FILES="${app_repo_dir}/${filename}"
 
     for app_file in $APP_FILES; do
-      if [[ -f "${app_file}" ]]; then
+      if [[ -f "${app_file}" ]] || [[ -d "${app_file}" ]]; then
         cp --archive "${app_file}" "${app_data_dir}"
       fi
     done
@@ -277,20 +302,29 @@ copy_app_files() {
 
 wait_for_tor_hs() {
   local -r app="${1}"
+  
+  # Check if the app's hidden service hostname
+  # Has been already generated and exit early
+  if [[ -f "${app_hidden_service_file}" ]]; then
+    return
+  fi
 
-  # Check only on start if a 'torrc` 
-  # config. file does NOT exist
-  if [[ ! -f "${app_torrc_file}" ]]; then
+  # Check that the app has the App Proxy service defined
+  local -r app_compose_file="${app_data_dir}/docker-compose.yml"
+  has_app_proxy_service=$(cat "${app_compose_file}" | yq ".services | has(\"${APP_PROXY_SERVICE_NAME}\")")
+
+  if [[ "${has_app_proxy_service}" == "false" ]]; then
     echo
-    >&2 echo "Warning: \"${app}\" is missing a 'torrc' config. file"
-    >&2 echo "         \"${app}\" will be inaccessible over Tor"
+    >&2 echo "Warning: \"${app}\" has no '${APP_PROXY_SERVICE_NAME}' defined"
+    >&2 echo "         \"${app}\" needs this to generate Tor HS"
     echo
+    return
   fi
 
   # If a tor service will start
   # and there is no existing tor hs hostname
   # Let's allow 10 seconds to generate it and then start the app
-  if [[ -f "${app_torrc_file}" ]] && [[ ! -f "${app_hidden_service_file}" ]]; then
+  if [[ "${REMOTE_TOR_ACCESS}" == "true" ]]; then
     echo "Generating hidden services for ${app}..."
     # We must first start the App Proxy
     # So that it's hostname is resolvable by Tor
@@ -327,8 +361,12 @@ start_app() {
   # Wait for Tor's HS hostname to exist
   wait_for_tor_hs "${app}"
 
+  execute_hook "${app}" "pre-start"
+
   # Start all the app's containers
   compose "${app}" up --detach
+
+  execute_hook "${app}" "post-start"
 }
 
 # Check that the app is installed
@@ -358,8 +396,7 @@ if [[ "$command" = "install" ]]; then
   # Copy all app files
   rsync --archive --verbose --exclude ".gitkeep" "${app_repo_dir}/." "${app_data_dir}"
 
-  # Copy default torrc.template file (if needed)
-  copy_default_torrc_template
+  execute_hook "${app}" "pre-install"
 
   # Source env.
   source_app "${app}"
@@ -378,6 +415,8 @@ if [[ "$command" = "install" ]]; then
   echo "Saving app ${app} in DB..."
   update_installed_apps add "${app}"
 
+  execute_hook "${app}" "post-install"
+
   echo "Successfully installed app ${app}"
   exit
 fi
@@ -386,6 +425,22 @@ fi
 if [[ "$command" = "uninstall" ]]; then
 
   must_be_installed_guard
+
+  execute_hook "${app}" "pre-uninstall"
+
+  # If a post uninstal hook exists
+  # Then make a copy before it's deleted below
+  app_hooks_dir="${UMBREL_ROOT}/app-data/${app}/hooks"
+  post_uninstall_app_hook="${app_hooks_dir}/post-uninstall"
+  if [[ -x "${post_uninstall_app_hook}" ]]; then
+    temp_post_uninstall_app_hook="/tmp/${app}-post-uninstall"
+
+    cp --archive "${post_uninstall_app_hook}" "${temp_post_uninstall_app_hook}"
+
+    post_uninstall_app_hook="${temp_post_uninstall_app_hook}"
+  else
+    post_uninstall_app_hook=""
+  fi
 
   echo "Removing images for app ${app}..."
   compose "${app}" down --rmi all --remove-orphans
@@ -398,6 +453,12 @@ if [[ "$command" = "uninstall" ]]; then
   echo "Removing app ${app} from DB..."
   update_installed_apps remove "${app}"
 
+  if [[ ! -z "${post_uninstall_app_hook}" ]]; then
+    "${post_uninstall_app_hook}" || true
+
+    rm -rf "${post_uninstall_app_hook}"
+  fi
+
   echo "Successfully uninstalled app ${app}"
   exit
 fi
@@ -405,8 +466,12 @@ fi
 # Stops an installed app
 if [[ "$command" = "stop" ]]; then
 
+  execute_hook "${app}" "pre-stop"
+
   echo "Stopping app ${app}..."
   compose "${app}" rm --force --stop
+
+  execute_hook "${app}" "post-stop"
 
   exit
 fi
@@ -458,9 +523,11 @@ if [[ "$command" = "update" ]]; then
   if [[ "$*" != *"--skip-stop"* ]]; then
     "${0}" "stop" "${app}"
   fi
+
+  execute_hook "${app}" "pre-update"
   
   # App updates will only copy files from this whitelist:
-  UPDATE_FILES_WHITELIST_PRE="docker-compose.yml *.template exports.sh torrc"
+  UPDATE_FILES_WHITELIST_PRE="docker-compose.yml *.template exports.sh torrc hooks"
 
   # We copy umbrel-app.yml after the app has started
   # That way the frontend knows the update has finished
@@ -471,9 +538,6 @@ if [[ "$command" = "update" ]]; then
 
   # Copy remaining files in the event of error or success
   trap "copy_app_files "${UPDATE_FILES_WHITELIST_POST}"; exit $?" INT TERM EXIT
-
-  # Copy default torrc.template file (if needed)
-  copy_default_torrc_template
 
   # Source env. after new exports.sh is copied (done above via 'copy_app_files')
   source_app "${app}"
@@ -490,13 +554,14 @@ if [[ "$command" = "update" ]]; then
 
   # Remove any old images we don't need anymore
   docker rmi $app_old_images || true
+
+  execute_hook "${app}" "post-update"
+
   exit
 fi
 
 # Passes all arguments to docker-compose
 if [[ "$command" = "compose" ]]; then
-  
-  must_be_installed_guard
 
   compose "${app}" ${args}
 
